name: Deploy to GOV.UK PaaS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy:
    name: Build and deploy to GOV.UK PaaS
    runs-on: ubuntu-latest
    concurrency: deploy-${{ github.ref }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set application environment (main branch)
        if: github.event_name == 'push'
        run: echo "CF_APP_NAME=teaching-vacancies-design-history" >> $GITHUB_ENV
      - name: Set application environment (Pull Request)
        if: github.event_name == 'pull_request'
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: echo "CF_APP_NAME=teaching-vacancies-design-history-pr-$PR_NUMBER" >> $GITHUB_ENV
      - uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE_NAME: teaching-vacancies-prototype
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Run Eleventy build
        run: npm run build --if-present
      - name: Push application
        run: cf push ${{ env.CF_APP_NAME }}
      - name: Post sticky pull request comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Review app deployed to <https://teaching-vacancies-design-history-pr-${{ github.event.number }}.london.cloudapps.digital>
